# Generated by Django 4.1.2 on 2022-11-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_number',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
